<2018-06-07 Thu>


Dear there,

   This is my repo about the implemention of essential data structures and algorithms in Java. Even though I learned DSA three years ago, I still think I do not grasp it well. So, I prefer to use this chance to strengthen my programming skills with the Java language.

* Asymptotic Notations
** Big-Theta
The theta notation bounds a functions from above and below, so it defines exact asymptotic behavior.

Big-Theta serve as both a lower bound and upper bound.

- Some English-language equivalents to Big-Theta notation
| Big-Theta                      | English                 |
|--------------------------------+-------------------------|
| Θ(c), for some constant c >= 0 | constant                |
| Θ(log n)                       | logarithmic in n        |
| Θ(n)                           | linear in n             |
| Θ(n log n)                     | linear-logarithmic in n |
| Θ(n²)                          | quadratic in n          |

** Big-O notation
To determine an /upper bound/ for the behavior od a function, that is, to determine how /bad/ the performance of the function can get.

** Big-Omega
To provide a crude /lower bound/ for a function.
To show how good a function can be.
* Data Structures
** Linked List
** Stack
- [[file:./DataStructures/Stackby2queues.java][Implementing a stack using two queues]]
** Queue
- [[file:./DataStructures/Queueby2stacks.java][Implementing a queue using two stacks]]
** Tree
- Print Left View of a given binary tree
** Heap
** Graph
* Algorithms
** Number Theory
** Binary Search

** Graphs Algorithms
- Depth First Search(DFS)
- Breadth First Search(BFS)
- Shortest Path
  + Dijkstra's Shortest Path
  + Floyd Warshall
- Minimum Spanning Tree
  + Kruskal's MST
  + Prim's MST
- Topological Sorting
- Maximum Flow
- Lowest Common Ancestor

** Dynamic Programming
- Longest Common Subsequence(LCS)
- Longest Increasing Subsequence
- Edit Distance
- Subset Sum Problem

** Searching and Sorting
** Divide and Conquer
- Quick Sort
- Merge Sort
** Misc
- Binary Indexed Tree
- Binary Search Tree
  + [[file:./Misc/checkBST.java][Check if a binary tree is BST or not]]
- Hashing
- Bit Algorithms
- String Algorithms
  + KMP

* Preparing for interviews
** 函数，字符串处理，二分法，排序算法入门
函数 Function
简单的排序算法 Simple Sort Algorithm
二分法 Binary Search I
二分法 Binary Search II
字符串 String

** 面向对象，类，链表，递归
面向对象编程概念 Object Oriented Programming
链表 Linked List
递归 Recursion
二分法深入&扫描线入门 Binary Search & Sweep-Line

** 二叉树，排序二叉树，遍历算法，分治算法
二叉树入门 Binary Tree Basics
二叉树上的遍历算法 Binary Tree Travesal
二分查找树 Binary Search Tree
二叉树上的分治算法 Divide and Conquer in Binary Tree I
二叉树上的分治算法 Divide and Conquer in Binary Tree II

** 分治算法，高级排序算法，快速选择算法，双指针算法
分治法, 高级排序算法 I
分治法, 高级排序算法 II
双指针算法一 Two Pointers I
双指针算法二 Two Pointers II
双指针算法三 & 快速选择算法 Two Pointers & Quick Select

** 常考数据结构：栈，队列，哈希表
队列和栈 Queue and Stack Basics
队列和栈 Queue and Stack Problems
哈希表 - 原理分析，具体实现 Open/Close Hashing
哈希表 - 应用 Application of Hash Table
堆入门 和 优先队列 Heap & Priority Queue

** 宽度优先搜索算法
宽度优先搜索 - 二叉树上的宽度搜索 Breadth First Search in Binary Tree
BFS之连通图及拓扑排序 Connected Graph & Topological Sorting
BFS之简单图求最短路径 Shortest Path in Simple Graph
BFS之矩阵中的宽搜 BFS in Matrix
宽度优先搜索 - 双向宽度优先搜索 Bi-directional BFS
** 深度优先搜索算法
深度优先搜索 - 组合型搜索 Depth First Search - Combination I
深度优先搜索 - 组合型搜索 Depth First Search - Combination II
深度优先搜索 - 排列型搜索 Depth First Search - Permutation
深度优先搜索 - 排列型搜索 Depth First Search - Permutation
深度优先搜索类问题 Depth First Search - Extension

** 动态规划入门
序列动态规划 Sequential Dynamic Programming I
序列动态规划 Sequential Dynamic Programming II
DP之坐标型动态规划 Coordinate Dynamic Programming
背包问题 Knapsack Problem
记忆化搜索 Memorization in Dynamic Programming

** 高级数据结构 字典树，并查集，堆
字典树原理实现 Trie Basics
字典树运用 Trie Problems
并查集原理与实现 Union Find I
并差集的运用 Union Find II
堆深入 Heap II
** 深度、宽度优先搜索加强
深度优先搜索的优化剪枝算法 Pruning Optimization in Depth First Search
深度优先搜索的优化剪枝算法 Pruning Optimization in Depth First Search
宽度优先搜索难题训练 Exercises for difficult problems in BFS
深度优先搜索难题训练 Exercises for difficult problems in DFS
A*算法 The A* Algorithm
** 双指针算法，动态规划算法加强，简历和模拟面试
区间动态规划 Dynamic Programming on Intervals
双序列动态规划 Dynamic Programming on Two Sequences
动态规划总结 Dynamic Programming Summary

* References
1. [https://www.geeksforgeeks.org/analysis-of-algorithms-set-3asymptotic-notations/]
